### ISSUE TITLE
Opname in de PTOLU

### ISSUE THREAD

**Issue by lathoub** [Geonovum/logboek-dataverwerkingen-voor-objecten#1]
Er wordt melding gemaakt dat na het succesvol beproeven van de standaard wordt deze voorgesteld voor opname in de PTOLU.

https://github.com/Geonovum/logboek-dataverwerkingen-voor-objecten/blob/6118daa99d546b4382be8b2527a71563d3ee97bf/respec/Samenvatting.md?plain=1#L5

Kan dat rechtstreeks? Gaat het niet van optioneel PTOLU naar effectief PTOLU?

**Comment by NielsHoffmann** [comment]
zelfde als #5 
ik sluit deze...
