### ISSUE TITLE
inleiding is meer de aanleiding

### ISSUE THREAD

**Issue by mrtn78** [Geonovum/logboek-dataverwerkingen-voor-objecten#10]
in H1 staat als inleiding https://geonovum.github.io/logboek-dataverwerkingen-voor-objecten/#H1
een tekst die meer de aanleiding beschrijft. Verder is voor een standaard niet relevant wat de budgetten en offertes waren. Ik zou de tekst aanpassen naar:

## Aanleiding
Het MIDO heeft aan BZK en Geonovum innovatiebudget toegewezen voor het onderwerp 'Standaard voor transparantie besluitvorming ' (IDO240584K). Hiermee onderkend men het grote belang dat de overheid verantwoording en transparantie biedt aan burgers en bedrijven over hoe zij handelt. Burgers en bedrijven dienen op de hoogte te zijn van de gebruikte gegevens en besluitvormingsprocessen van de overheid. Hiervoor worden niet alleen persoonsgegevens maar bijvoorbeeld ook data over objecten uit de fysieke leefomgeving gebruikt.

**Comment by NielsHoffmann** [comment]
Wat mij betreft is het een onderzoek, en is het daarmee geen uitgemaakte zaak dat dit tot een standaard leidt. Het kan ook zijn dat het resultaat van het onderzoek is dat er geen uitbreiding op de standaard nodig is. Alleen een 'toepassingsprofiel' en/of een extensie specifiek voor inzage van (geo)object logging.
