### ISSUE TITLE
Discrepantie leeswijzer, FAQ en samenvatting

### ISSUE THREAD

**Issue by MirianvAnsem** [Geonovum/logboek-dataverwerkingen-voor-objecten#5]
Uit samenvatting:
Na het succesvol beproeven van de standaard wordt deze voorgesteld voor opname in de [‘Pas toe of leg uit’-lijst van het Forum voor Standaardisatie](https://forumstandaardisatie.nl/pas-toe-leg-uit-beleid).

In leeswijzer is voorafgaand hieraan ook de MIDO-vaststelling benoemd. Nagaan welk pad gekozen wordt en in alle documenten zo opnemen.

**Comment by NielsHoffmann** [comment]
eens. ik denk dat het goed is om de (geo)objecten standaard als uitbreiding te positioneren. en de vaststelling ervan gelijk te trekken met de core. 
ook denk ik dat we wat met het 'volwassenheidsniveau' moeten en met extensies voor raadplegen.

**Comment by NielsHoffmann** [comment]
voorstel: PTOLU eruit. Duidelijk maken dat het in dit geval een onderzoek betreft en dat er daarna aanvullende stappen mogelijk zijn,
