### ISSUE TITLE
digitale tweelingen en de standaard

### ISSUE THREAD

**Issue by MirianvAnsem** [Geonovum/logboek-dataverwerkingen-voor-objecten#8]
2.4.1. Eerste zin: Bij het implementeren van de loggingstandaard speelt de dynamiek van het digitale tweelingen ecosysteem een grote rol. 

Zin is onduidelijk. Wordt er bedoeld dat er bij gebruik van de standaard op digitale tweelingen rekening moet worden gehouden met de dynamiek van het model of iets anders?

**Comment by NielsHoffmann** [comment]
ongeveer hetzelfde als #2
